### ISSUE TITLE
I can not run the setup.py file in my rasbian python terminal

### ISSUE THREAD

**Issue by Rens12345** [stevemarple/python-MCP342x#1]
When i tried run 'sudo python MCP342x install' in my cd mcp342x terminal window it gave me an error.  it said to me  : 'compilation terminated. error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1 '. besides this error it has also problems with finding a package called 'libffi'.

How can i solve these problems?

**Comment by stevemarple** [comment]
The module requires the `smbus-cffi` Python module. The easiest way to install this on Raspbian is

    sudo apt-get install python-smbus 

To prevent the install script from updating this outside of apt you may wish to run the installer without checking for dependencies (smbus is the sole dependency). I think you can do this with

    sudo python setup.py install  --no-deps

**Comment by Rens12345** [comment]
The smbus python module was not the problem for me, because I already had that module in my rasbian python version. My problem was with finding and installing the MCP342x python module. 

Since i couldn't find that module i went with another program that eventually worked out great for me.

[mcp3424 python code.docx](https://github.com/stevemarple/python-MCP342x/files/992138/mcp3424.python.code.docx)
